AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/bundle/**/*'
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/NestedPercentLiteral:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'script/benchmark'
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 8

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/CombinableLoops:
  Exclude: ['spec/**/*.rb']

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FileRead:
  Enabled: false

Style/FileWrite:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/ParallelAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'

Style/RedundantArgument:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SignalException:
  EnforcedStyle: semantic

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
