sudo: false
language: ruby
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'
  - 'jruby-1.7.26'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.5.0'
script: bundle exec rspec
env:
  - RUGGED=0
  - RUGGED=1
matrix:
  include:
    - env: RUBOCOP=✓
      rvm: '2'
      script: bundle exec rubocop
    - env: BENCHMARK=✓ RUGGED=1
      rvm: default
      script:
        - RUGGED=0 bundle exec script/benchmark
        - RUGGED=1 bundle exec script/benchmark
    - env: CHECK_RUBIES=✓
      rvm: '2'
      script: bundle exec travis_check_rubies
  exclude:
    - rvm: '1.8.7-p371'
      env: RUGGED=1
    - rvm: '1.9.3-p551'
      env: RUGGED=1
    - rvm: 'jruby-1.7.26'
      env: RUGGED=1
    - rvm: 'jruby-9.0.5.0'
      env: RUGGED=1
    - rvm: 'jruby-9.1.5.0'
      env: RUGGED=1
