language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - '2.0'
  - '2.1'
  - '2.2'
  - jruby-18mode
  - jruby-19mode
  - ree
script:
  if [ -z "$RUBOCOP" ]; then
    bundle exec rspec
  ; else
    bundle exec rubocop
  ; fi
env:
  -
  - RUGGED=1
matrix:
  fast_finish: true
  include:
    - env: RUBOCOP=true
      rvm: default
  exclude:
    - rvm: 1.8.7
      env: RUGGED=1
    - rvm: jruby-18mode
      env: RUGGED=1
    - rvm: jruby-19mode
      env: RUGGED=1
    - rvm: ree
      env: RUGGED=1
