sudo: false
dist: trusty
language: ruby
rvm:
  - '1.9.3-p551'
  - '2.2.10'
  - '2.3.8'
  - '2.4.9'
  - '2.5.7'
  - '2.6.5'
  - '2.7.0'
  - 'jruby-9.1.17.0'
  - 'jruby-9.2.7.0'
script: bundle exec rspec
before_install:
  - gem install rubygems-update || gem install rubygems-update --version '< 3'
  - gem update --system
  - gem install bundler || gem install bundler --version '< 2'
env:
  - DRIVER=git
  - DRIVER=rugged
matrix:
  include:
    - env: RUBOCOP=1
      rvm: '2.6.5'
      script: bundle exec rubocop
    - env: BENCHMARK=1
      rvm: '2.6.5'
      install: DRIVER=rugged bundle install --jobs=3 --retry=3
      script:
        - DRIVER=git bundle exec script/benchmark
        - DRIVER=rugged bundle exec script/benchmark
    - env: CHECK_RUBIES=1
      rvm: '2.6.5'
      script: bundle exec travis_check_rubies
  exclude:
    - rvm: '1.9.3-p551'
      env: DRIVER=rugged
    - rvm: 'jruby-9.1.17.0'
      env: DRIVER=rugged
    - rvm: 'jruby-9.2.7.0'
      env: DRIVER=rugged
  allow_failures:
    - rvm: 'jruby-9.1.17.0'
      env: DRIVER=git
    - rvm: 'jruby-9.2.7.0'
      env: DRIVER=git
