sudo: false
language: ruby
rvm:
  - '1.9.3-p551'
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'
  - 'jruby-1.7.26'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.5.0'
script: bundle exec rspec
env:
  - DRIVER=git
  - DRIVER=rugged
matrix:
  include:
    - env: RUBOCOP=✓
      rvm: '2'
      script: bundle exec rubocop
    - env: BENCHMARK=✓ DRIVER=rugged
      rvm: '2'
      script:
        - DRIVER=git bundle exec script/benchmark
        - DRIVER=rugged bundle exec script/benchmark
    - env: CHECK_RUBIES=✓
      rvm: '2'
      script: bundle exec travis_check_rubies
  exclude:
    - rvm: '1.9.3-p551'
      env: DRIVER=rugged
    - rvm: 'jruby-1.7.26'
      env: DRIVER=rugged
    - rvm: 'jruby-9.0.5.0'
      env: DRIVER=rugged
    - rvm: 'jruby-9.1.5.0'
      env: DRIVER=rugged
  allow_failures:
    - rvm: 'jruby-9.0.5.0'
      env: DRIVER=git
    - rvm: 'jruby-9.1.5.0'
      env: DRIVER=git
