sudo: false
language: ruby
rvm:
  - '1.8'
  - '1.9'
  - '2.0'
  - '2.1'
  - '2.2'
  - jruby-18mode
  - jruby-19mode
  - ree
script:
  if [ -n "$RUBOCOP" ]; then
    bundle exec rubocop
  ; elif [ -n "$BENCHMARK" ]; then
    RUGGED=0 bundle exec script/benchmark; RUGGED=1 bundle exec script/benchmark
  ; else
    bundle exec rspec
  ; fi
env:
  -
  - RUGGED=1
matrix:
  fast_finish: true
  include:
    - env: RUBOCOP=true
      rvm: default
    - env: BENCHMARK=true RUGGED=1
      rvm: default
  exclude:
    - rvm: '1.8'
      env: RUGGED=1
    - rvm: jruby-18mode
      env: RUGGED=1
    - rvm: jruby-19mode
      env: RUGGED=1
    - rvm: ree
      env: RUGGED=1
