sudo: false
language: ruby
rvm:
  - '1.9.3-p551'
  - '2.2.10'
  - '2.3.8'
  - '2.4.5'
  - '2.5.3'
  - 'jruby-1.7.26'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.9.0'
script: bundle exec rspec
before_install:
  - gem install bundler
  - ruby -e 'require "rubygems"; require "bundler/inline"; gemfile{ source "https://rubygems.org"; gem "rubygems-update" }' # get compatible version of rubygems-update
  - gem update --system
env:
  - DRIVER=git
  - DRIVER=rugged
matrix:
  include:
    - env: RUBOCOP=✓
      rvm: '2.5.3'
      script: bundle exec rubocop
    - env: BENCHMARK=✓
      rvm: '2.5.3'
      install: DRIVER=rugged bundle install --jobs=3 --retry=3
      script:
        - DRIVER=git bundle exec script/benchmark
        - DRIVER=rugged bundle exec script/benchmark
    - env: CHECK_RUBIES=✓
      rvm: '2.5.3'
      script: bundle exec travis_check_rubies
  exclude:
    - rvm: '1.9.3-p551'
      env: DRIVER=rugged
    - rvm: 'jruby-1.7.26'
      env: DRIVER=rugged
    - rvm: 'jruby-9.0.5.0'
      env: DRIVER=rugged
    - rvm: 'jruby-9.1.9.0'
      env: DRIVER=rugged
  allow_failures:
    - rvm: 'jruby-9.0.5.0'
      env: DRIVER=git
    - rvm: 'jruby-9.1.9.0'
      env: DRIVER=git
